language: c
dist: trusty
env:
  global:
    - CI40_SDK="creator-sdk-1"
    - CI40_URL="http://downloads.creatordev.io/creator-openwrt/v1/pistachio/marduk/"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git libncurses5-dev libncursesw5-dev zlib1g-dev libssl-dev gawk subversion device-tree-compiler bsdmainutils bc rsync
script:
  - wget "$CI40_URL$CI40_SDK.tar.bz2"
  - mkdir openwrt-sdk && tar -xvf $CI40_SDK.tar.bz2 -C openwrt-sdk/ --strip-components 1
  - rm $CI40_SDK.tar.bz2
  - mkdir myworkspace && cd $HOME/myworkspace
  - git clone https://github.com/CreatorDev/w1-switchcounter.git
  - workspacedir=$(readlink -f ./)
  - cd $HOME/openwrt-sdk/creator-sdk
  - echo src-link myworkspace $workspacedir >> feeds.conf.default
  - ./scripts/feeds update -a && ./scripts/feeds install -a
  - cd $HOME/openwrt-sdk/creator-sdk && make package/w1-switchcounter/compile